-- ============================================================================
-- OBSERVE BY SNOWFLAKE - ENTERPRISE OBSERVABILITY PLATFORM
-- Production-Grade Implementation for AI Data Cloud
-- ============================================================================
-- Architecture: Telemetry Lakehouse with AI SRE Automation
-- Version: 1.0.0 | Date: 2026-05-21
-- ============================================================================

-- ============================================================================
-- SECTION 1: FOUNDATION - DATABASE & SCHEMA HIERARCHY
-- ============================================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS OBSERVABILITY_PLATFORM;
CREATE DATABASE IF NOT EXISTS OBSERVABILITY_PLATFORM_DEV;
CREATE DATABASE IF NOT EXISTS OBSERVABILITY_PLATFORM_STAGING;

USE DATABASE OBSERVABILITY_PLATFORM;

CREATE SCHEMA IF NOT EXISTS RAW_TELEMETRY;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS AI_SRE;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS CONTEXT_GRAPH;
CREATE SCHEMA IF NOT EXISTS ALERTING;
CREATE SCHEMA IF NOT EXISTS COST_OPS;

-- ============================================================================
-- SECTION 2: RBAC FRAMEWORK - LEAST PRIVILEGE ACCESS
-- ============================================================================

CREATE ROLE IF NOT EXISTS OBSERVABILITY_ADMIN;
CREATE ROLE IF NOT EXISTS OBSERVABILITY_ENGINEER;
CREATE ROLE IF NOT EXISTS OBSERVABILITY_ANALYST;
CREATE ROLE IF NOT EXISTS OBSERVABILITY_VIEWER;
CREATE ROLE IF NOT EXISTS AI_SRE_AGENT;
CREATE ROLE IF NOT EXISTS TELEMETRY_INGESTOR;
CREATE ROLE IF NOT EXISTS GOVERNANCE_OFFICER;

GRANT ROLE OBSERVABILITY_VIEWER TO ROLE OBSERVABILITY_ANALYST;
GRANT ROLE OBSERVABILITY_ANALYST TO ROLE OBSERVABILITY_ENGINEER;
GRANT ROLE OBSERVABILITY_ENGINEER TO ROLE OBSERVABILITY_ADMIN;
GRANT ROLE OBSERVABILITY_ADMIN TO ROLE SYSADMIN;
GRANT ROLE AI_SRE_AGENT TO ROLE OBSERVABILITY_ADMIN;
GRANT ROLE TELEMETRY_INGESTOR TO ROLE OBSERVABILITY_ENGINEER;
GRANT ROLE GOVERNANCE_OFFICER TO ROLE OBSERVABILITY_ADMIN;

GRANT USAGE ON DATABASE OBSERVABILITY_PLATFORM TO ROLE OBSERVABILITY_VIEWER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OBSERVABILITY_PLATFORM TO ROLE OBSERVABILITY_VIEWER;
GRANT SELECT ON FUTURE TABLES IN DATABASE OBSERVABILITY_PLATFORM TO ROLE OBSERVABILITY_VIEWER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE OBSERVABILITY_PLATFORM TO ROLE OBSERVABILITY_VIEWER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN DATABASE OBSERVABILITY_PLATFORM TO ROLE OBSERVABILITY_VIEWER;

GRANT CREATE TABLE ON SCHEMA OBSERVABILITY_PLATFORM.RAW_TELEMETRY TO ROLE TELEMETRY_INGESTOR;
GRANT INSERT ON FUTURE TABLES IN SCHEMA OBSERVABILITY_PLATFORM.RAW_TELEMETRY TO ROLE TELEMETRY_INGESTOR;

-- ============================================================================
-- SECTION 3: WAREHOUSE STRATEGY
-- ============================================================================

CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 4
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Telemetry ingestion workloads';

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
    WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Bronze-Silver-Gold transformations';

CREATE WAREHOUSE IF NOT EXISTS AI_SRE_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'ECONOMY'
    COMMENT = 'AI SRE inference and analysis';

CREATE WAREHOUSE IF NOT EXISTS DASHBOARD_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Streamlit dashboard queries';

-- Resource Monitors
CREATE RESOURCE MONITOR IF NOT EXISTS OBSERVABILITY_MONITOR
    WITH CREDIT_QUOTA = 5000
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE INGEST_WH SET RESOURCE_MONITOR = OBSERVABILITY_MONITOR;
ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = OBSERVABILITY_MONITOR;
ALTER WAREHOUSE AI_SRE_WH SET RESOURCE_MONITOR = OBSERVABILITY_MONITOR;

-- ============================================================================
-- SECTION 4: RAW TELEMETRY INGESTION TABLES (BRONZE LAYER)
-- ============================================================================

USE SCHEMA RAW_TELEMETRY;

CREATE TABLE IF NOT EXISTS RAW_LOGS (
    INGESTION_ID VARCHAR(64) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(256) NOT NULL,
    LOG_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    SEVERITY VARCHAR(16),
    SERVICE_NAME VARCHAR(256),
    ENVIRONMENT VARCHAR(64),
    REGION VARCHAR(64),
    TRACE_ID VARCHAR(64),
    SPAN_ID VARCHAR(64),
    HOST VARCHAR(256),
    CONTAINER_ID VARCHAR(128),
    POD_NAME VARCHAR(256),
    NAMESPACE VARCHAR(128),
    LOG_MESSAGE TEXT,
    STRUCTURED_DATA VARIANT,
    RESOURCE_ATTRIBUTES VARIANT,
    LOG_ATTRIBUTES VARIANT
)
CLUSTER BY (LOG_TIMESTAMP::DATE, SERVICE_NAME, SEVERITY)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Raw log events from all sources via OpenTelemetry';

CREATE TABLE IF NOT EXISTS RAW_METRICS (
    INGESTION_ID VARCHAR(64) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(256) NOT NULL,
    METRIC_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    METRIC_NAME VARCHAR(512) NOT NULL,
    METRIC_TYPE VARCHAR(32),
    METRIC_VALUE DOUBLE,
    METRIC_UNIT VARCHAR(64),
    SERVICE_NAME VARCHAR(256),
    ENVIRONMENT VARCHAR(64),
    REGION VARCHAR(64),
    HOST VARCHAR(256),
    DIMENSIONS VARIANT,
    RESOURCE_ATTRIBUTES VARIANT,
    EXEMPLARS VARIANT
)
CLUSTER BY (METRIC_TIMESTAMP::DATE, METRIC_NAME, SERVICE_NAME)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Raw metric data points from infrastructure and applications';

CREATE TABLE IF NOT EXISTS RAW_TRACES (
    INGESTION_ID VARCHAR(64) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(256),
    TRACE_ID VARCHAR(64) NOT NULL,
    SPAN_ID VARCHAR(64) NOT NULL,
    PARENT_SPAN_ID VARCHAR(64),
    SPAN_NAME VARCHAR(512),
    SPAN_KIND VARCHAR(32),
    SERVICE_NAME VARCHAR(256) NOT NULL,
    ENVIRONMENT VARCHAR(64),
    REGION VARCHAR(64),
    START_TIME TIMESTAMP_NTZ NOT NULL,
    END_TIME TIMESTAMP_NTZ,
    DURATION_MS DOUBLE,
    STATUS_CODE VARCHAR(16),
    STATUS_MESSAGE TEXT,
    SPAN_ATTRIBUTES VARIANT,
    RESOURCE_ATTRIBUTES VARIANT,
    EVENTS VARIANT,
    LINKS VARIANT
)
CLUSTER BY (START_TIME::DATE, SERVICE_NAME, TRACE_ID)
DATA_RETENTION_TIME_IN_DAYS = 30
COMMENT = 'Distributed trace spans from OpenTelemetry instrumented services';

CREATE TABLE IF NOT EXISTS RAW_K8S_EVENTS (
    INGESTION_ID VARCHAR(64) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    CLUSTER_NAME VARCHAR(256) NOT NULL,
    NAMESPACE VARCHAR(128),
    EVENT_TYPE VARCHAR(32),
    REASON VARCHAR(256),
    OBJECT_KIND VARCHAR(64),
    OBJECT_NAME VARCHAR(256),
    MESSAGE TEXT,
    SOURCE_COMPONENT VARCHAR(256),
    COUNT INT,
    FIRST_TIMESTAMP TIMESTAMP_NTZ,
    LAST_TIMESTAMP TIMESTAMP_NTZ,
    METADATA VARIANT
)
CLUSTER BY (EVENT_TIMESTAMP::DATE, CLUSTER_NAME, NAMESPACE)
DATA_RETENTION_TIME_IN_DAYS = 90;

CREATE TABLE IF NOT EXISTS RAW_SNOWFLAKE_TELEMETRY (
    INGESTION_ID VARCHAR(64) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TELEMETRY_TYPE VARCHAR(64) NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    WAREHOUSE_NAME VARCHAR(256),
    QUERY_ID VARCHAR(64),
    USER_NAME VARCHAR(256),
    ROLE_NAME VARCHAR(256),
    DATABASE_NAME VARCHAR(256),
    SCHEMA_NAME VARCHAR(256),
    EXECUTION_TIME_MS DOUBLE,
    BYTES_SCANNED BIGINT,
    ROWS_PRODUCED BIGINT,
    CREDITS_USED DOUBLE,
    QUERY_TEXT TEXT,
    ERROR_CODE VARCHAR(16),
    ERROR_MESSAGE TEXT,
    ADDITIONAL_METADATA VARIANT
)
CLUSTER BY (EVENT_TIMESTAMP::DATE, TELEMETRY_TYPE, WAREHOUSE_NAME)
DATA_RETENTION_TIME_IN_DAYS = 90;

CREATE TABLE IF NOT EXISTS RAW_CLOUD_TELEMETRY (
    INGESTION_ID VARCHAR(64) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CLOUD_PROVIDER VARCHAR(16) NOT NULL,
    SERVICE_NAME VARCHAR(256) NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    REGION VARCHAR(64),
    ACCOUNT_ID VARCHAR(128),
    RESOURCE_TYPE VARCHAR(128),
    RESOURCE_ID VARCHAR(512),
    EVENT_TYPE VARCHAR(128),
    METRIC_NAME VARCHAR(256),
    METRIC_VALUE DOUBLE,
    DIMENSIONS VARIANT,
    RAW_EVENT VARIANT
)
CLUSTER BY (EVENT_TIMESTAMP::DATE, CLOUD_PROVIDER, SERVICE_NAME)
DATA_RETENTION_TIME_IN_DAYS = 90;

CREATE TABLE IF NOT EXISTS RAW_CICD_TELEMETRY (
    INGESTION_ID VARCHAR(64) DEFAULT UUID_STRING(),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PIPELINE_SYSTEM VARCHAR(64) NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    PIPELINE_ID VARCHAR(256),
    PIPELINE_NAME VARCHAR(512),
    JOB_NAME VARCHAR(512),
    STAGE_NAME VARCHAR(256),
    STATUS VARCHAR(32),
    DURATION_MS BIGINT,
    COMMIT_SHA VARCHAR(64),
    BRANCH VARCHAR(256),
    REPOSITORY VARCHAR(512),
    TRIGGER_TYPE VARCHAR(64),
    ARTIFACT_METADATA VARIANT,
    TEST_RESULTS VARIANT,
    DEPLOYMENT_METADATA VARIANT
)
CLUSTER BY (EVENT_TIMESTAMP::DATE, PIPELINE_SYSTEM, STATUS)
DATA_RETENTION_TIME_IN_DAYS = 90;

-- ============================================================================
-- SECTION 5: INGESTION INFRASTRUCTURE
-- ============================================================================

CREATE STAGE IF NOT EXISTS OBSERVABILITY_PLATFORM.RAW_TELEMETRY.TELEMETRY_LANDING_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Landing stage for batch telemetry file ingestion';

CREATE FILE FORMAT IF NOT EXISTS OBSERVABILITY_PLATFORM.RAW_TELEMETRY.OTEL_JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_NULL_VALUES = FALSE
    IGNORE_UTF8_ERRORS = TRUE
    COMMENT = 'OpenTelemetry JSON format for log/metric/trace ingestion';

CREATE FILE FORMAT IF NOT EXISTS OBSERVABILITY_PLATFORM.RAW_TELEMETRY.TELEMETRY_PARQUET_FORMAT
    TYPE = 'PARQUET'
    COMPRESSION = 'SNAPPY'
    COMMENT = 'Parquet format for high-volume telemetry batches';

CREATE PIPE IF NOT EXISTS OBSERVABILITY_PLATFORM.RAW_TELEMETRY.LOGS_SNOWPIPE
    AUTO_INGEST = TRUE
    COMMENT = 'Auto-ingest pipe for log files from external stage'
AS
    COPY INTO OBSERVABILITY_PLATFORM.RAW_TELEMETRY.RAW_LOGS (
        SOURCE_SYSTEM, LOG_TIMESTAMP, SEVERITY, SERVICE_NAME,
        ENVIRONMENT, REGION, TRACE_ID, SPAN_ID, HOST,
        CONTAINER_ID, POD_NAME, NAMESPACE, LOG_MESSAGE,
        STRUCTURED_DATA, RESOURCE_ATTRIBUTES, LOG_ATTRIBUTES
    )
    FROM (
        SELECT
            $1:source_system::VARCHAR,
            $1:timestamp::TIMESTAMP_NTZ,
            $1:severity::VARCHAR,
            $1:service_name::VARCHAR,
            $1:environment::VARCHAR,
            $1:region::VARCHAR,
            $1:trace_id::VARCHAR,
            $1:span_id::VARCHAR,
            $1:host::VARCHAR,
            $1:container_id::VARCHAR,
            $1:pod_name::VARCHAR,
            $1:namespace::VARCHAR,
            $1:message::TEXT,
            $1:structured_data::VARIANT,
            $1:resource_attributes::VARIANT,
            $1:log_attributes::VARIANT
        FROM @OBSERVABILITY_PLATFORM.RAW_TELEMETRY.TELEMETRY_LANDING_STAGE/logs/
    )
    FILE_FORMAT = (FORMAT_NAME = 'OTEL_JSON_FORMAT');

-- ============================================================================
-- SECTION 6: DYNAMIC TABLES - SILVER LAYER (Enriched Telemetry)
-- ============================================================================

USE SCHEMA SILVER;

CREATE OR REPLACE DYNAMIC TABLE DT_ENRICHED_LOGS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = TRANSFORM_WH
    REFRESH_MODE = INCREMENTAL
AS
    SELECT
        r.INGESTION_ID,
        r.LOG_TIMESTAMP,
        r.SEVERITY,
        r.SERVICE_NAME,
        r.ENVIRONMENT,
        r.REGION,
        r.TRACE_ID,
        r.SPAN_ID,
        r.HOST,
        r.CONTAINER_ID,
        r.POD_NAME,
        r.NAMESPACE,
        r.LOG_MESSAGE,
        r.STRUCTURED_DATA,
        r.RESOURCE_ATTRIBUTES,
        CASE
            WHEN r.SEVERITY IN ('FATAL', 'CRITICAL', 'EMERGENCY') THEN 1
            WHEN r.SEVERITY = 'ERROR' THEN 2
            WHEN r.SEVERITY = 'WARN' THEN 3
            WHEN r.SEVERITY = 'INFO' THEN 4
            WHEN r.SEVERITY = 'DEBUG' THEN 5
            ELSE 6
        END AS SEVERITY_RANK,
        DATE_TRUNC('HOUR', r.LOG_TIMESTAMP) AS LOG_HOUR,
        DATE_TRUNC('DAY', r.LOG_TIMESTAMP) AS LOG_DATE,
        LENGTH(r.LOG_MESSAGE) AS MESSAGE_LENGTH,
        CONTAINS(LOWER(r.LOG_MESSAGE), 'error') OR
        CONTAINS(LOWER(r.LOG_MESSAGE), 'exception') OR
        CONTAINS(LOWER(r.LOG_MESSAGE), 'failed') AS IS_ERROR_INDICATOR
    FROM OBSERVABILITY_PLATFORM.RAW_TELEMETRY.RAW_LOGS r
    WHERE r.LOG_TIMESTAMP >= DATEADD('DAY', -90, CURRENT_TIMESTAMP());

CREATE OR REPLACE DYNAMIC TABLE DT_ENRICHED_METRICS
    TARGET_LAG = '2 minutes'
    WAREHOUSE = TRANSFORM_WH
    REFRESH_MODE = INCREMENTAL
AS
    SELECT
        r.INGESTION_ID,
        r.METRIC_TIMESTAMP,
        r.METRIC_NAME,
        r.METRIC_TYPE,
        r.METRIC_VALUE,
        r.METRIC_UNIT,
        r.SERVICE_NAME,
        r.ENVIRONMENT,
        r.REGION,
        r.HOST,
        r.DIMENSIONS,
        r.RESOURCE_ATTRIBUTES,
        DATE_TRUNC('MINUTE', r.METRIC_TIMESTAMP) AS METRIC_MINUTE,
        DATE_TRUNC('HOUR', r.METRIC_TIMESTAMP) AS METRIC_HOUR,
        DATE_TRUNC('DAY', r.METRIC_TIMESTAMP) AS METRIC_DATE
    FROM OBSERVABILITY_PLATFORM.RAW_TELEMETRY.RAW_METRICS r
    WHERE r.METRIC_TIMESTAMP >= DATEADD('DAY', -365, CURRENT_TIMESTAMP());

CREATE OR REPLACE DYNAMIC TABLE DT_ENRICHED_TRACES
    TARGET_LAG = '2 minutes'
    WAREHOUSE = TRANSFORM_WH
    REFRESH_MODE = INCREMENTAL
AS
    SELECT
        r.TRACE_ID,
        r.SPAN_ID,
        r.PARENT_SPAN_ID,
        r.SPAN_NAME,
        r.SPAN_KIND,
        r.SERVICE_NAME,
        r.ENVIRONMENT,
        r.REGION,
        r.START_TIME,
        r.END_TIME,
        r.DURATION_MS,
        r.STATUS_CODE,
        r.STATUS_MESSAGE,
        r.SPAN_ATTRIBUTES,
        r.RESOURCE_ATTRIBUTES,
        r.EVENTS,
        r.LINKS,
        CASE
            WHEN r.STATUS_CODE = 'ERROR' THEN TRUE
            ELSE FALSE
        END AS IS_ERROR,
        CASE
            WHEN r.PARENT_SPAN_ID IS NULL THEN TRUE
            ELSE FALSE
        END AS IS_ROOT_SPAN,
        CASE
            WHEN r.DURATION_MS > 5000 THEN 'CRITICAL'
            WHEN r.DURATION_MS > 2000 THEN 'SLOW'
            WHEN r.DURATION_MS > 1000 THEN 'MODERATE'
            ELSE 'NORMAL'
        END AS LATENCY_BUCKET,
        DATE_TRUNC('HOUR', r.START_TIME) AS TRACE_HOUR
    FROM OBSERVABILITY_PLATFORM.RAW_TELEMETRY.RAW_TRACES r
    WHERE r.START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP());

-- ============================================================================
-- SECTION 7: DYNAMIC TABLES - GOLD LAYER (Aggregated Analytics)
-- ============================================================================

USE SCHEMA GOLD;

CREATE OR REPLACE DYNAMIC TABLE DT_SERVICE_HEALTH_SCORE
    TARGET_LAG = '5 minutes'
    WAREHOUSE = TRANSFORM_WH
AS
    SELECT
        DATE_TRUNC('HOUR', m.METRIC_TIMESTAMP) AS HOUR_BUCKET,
        m.SERVICE_NAME,
        m.ENVIRONMENT,
        m.REGION,
        COUNT(DISTINCT CASE WHEN m.METRIC_NAME = 'http.request.count' THEN m.INGESTION_ID END) AS REQUEST_COUNT,
        AVG(CASE WHEN m.METRIC_NAME = 'http.request.duration' THEN m.METRIC_VALUE END) AS AVG_LATENCY_MS,
        SUM(CASE WHEN m.METRIC_NAME = 'http.request.error_count' THEN m.METRIC_VALUE ELSE 0 END) AS ERROR_COUNT,
        CASE
            WHEN SUM(CASE WHEN m.METRIC_NAME = 'http.request.count' THEN m.METRIC_VALUE ELSE 0 END) = 0 THEN 0
            ELSE 1.0 - (SUM(CASE WHEN m.METRIC_NAME = 'http.request.error_count' THEN m.METRIC_VALUE ELSE 0 END) /
                        NULLIF(SUM(CASE WHEN m.METRIC_NAME = 'http.request.count' THEN m.METRIC_VALUE ELSE 0 END), 0))
        END AS SUCCESS_RATE,
        GREATEST(0, LEAST(100,
            (COALESCE(1.0 - (SUM(CASE WHEN m.METRIC_NAME = 'http.request.error_count' THEN m.METRIC_VALUE ELSE 0 END) /
                NULLIF(SUM(CASE WHEN m.METRIC_NAME = 'http.request.count' THEN m.METRIC_VALUE ELSE 0 END), 0)), 1) * 40) +
            (CASE WHEN AVG(CASE WHEN m.METRIC_NAME = 'http.request.duration' THEN m.METRIC_VALUE END) < 200 THEN 30
                  WHEN AVG(CASE WHEN m.METRIC_NAME = 'http.request.duration' THEN m.METRIC_VALUE END) < 500 THEN 20
                  WHEN AVG(CASE WHEN m.METRIC_NAME = 'http.request.duration' THEN m.METRIC_VALUE END) < 1000 THEN 10
                  ELSE 0 END) +
            (CASE WHEN SUM(CASE WHEN m.METRIC_NAME = 'http.request.count' THEN m.METRIC_VALUE ELSE 0 END) > 100 THEN 30
                  WHEN SUM(CASE WHEN m.METRIC_NAME = 'http.request.count' THEN m.METRIC_VALUE ELSE 0 END) > 10 THEN 20
                  ELSE 10 END)
        )) AS HEALTH_SCORE
    FROM OBSERVABILITY_PLATFORM.SILVER.DT_ENRICHED_METRICS m
    WHERE m.METRIC_TIMESTAMP >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
    GROUP BY ALL;

CREATE OR REPLACE DYNAMIC TABLE DT_INCIDENT_METRICS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = TRANSFORM_WH
AS
    SELECT
        DATE_TRUNC('DAY', l.LOG_TIMESTAMP) AS INCIDENT_DATE,
        l.SERVICE_NAME,
        l.ENVIRONMENT,
        COUNT(CASE WHEN l.SEVERITY IN ('ERROR', 'FATAL', 'CRITICAL') THEN 1 END) AS ERROR_COUNT,
        COUNT(DISTINCT l.TRACE_ID) AS AFFECTED_TRACES,
        MIN(l.LOG_TIMESTAMP) AS FIRST_ERROR_AT,
        MAX(l.LOG_TIMESTAMP) AS LAST_ERROR_AT,
        DATEDIFF('MINUTE', MIN(l.LOG_TIMESTAMP), MAX(l.LOG_TIMESTAMP)) AS DURATION_MINUTES,
        COUNT(DISTINCT l.HOST) AS AFFECTED_HOSTS
    FROM OBSERVABILITY_PLATFORM.SILVER.DT_ENRICHED_LOGS l
    WHERE l.SEVERITY IN ('ERROR', 'FATAL', 'CRITICAL')
        AND l.LOG_TIMESTAMP >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
    GROUP BY ALL;

CREATE OR REPLACE DYNAMIC TABLE DT_SLO_COMPLIANCE
    TARGET_LAG = '10 minutes'
    WAREHOUSE = TRANSFORM_WH
AS
    SELECT
        DATE_TRUNC('DAY', t.START_TIME) AS SLO_DATE,
        t.SERVICE_NAME,
        t.ENVIRONMENT,
        COUNT(*) AS TOTAL_REQUESTS,
        SUM(CASE WHEN t.IS_ERROR THEN 1 ELSE 0 END) AS FAILED_REQUESTS,
        SUM(CASE WHEN t.DURATION_MS > 2000 THEN 1 ELSE 0 END) AS SLOW_REQUESTS,
        1.0 - (SUM(CASE WHEN t.IS_ERROR THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0)) AS AVAILABILITY_SLI,
        1.0 - (SUM(CASE WHEN t.DURATION_MS > 2000 THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0)) AS LATENCY_SLI,
        AVG(t.DURATION_MS) AS P50_LATENCY,
        APPROX_PERCENTILE(t.DURATION_MS, 0.95) AS P95_LATENCY,
        APPROX_PERCENTILE(t.DURATION_MS, 0.99) AS P99_LATENCY
    FROM OBSERVABILITY_PLATFORM.SILVER.DT_ENRICHED_TRACES t
    WHERE t.IS_ROOT_SPAN = TRUE
        AND t.START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
    GROUP BY ALL;

CREATE OR REPLACE DYNAMIC TABLE DT_COST_ANALYTICS
    TARGET_LAG = '30 minutes'
    WAREHOUSE = TRANSFORM_WH
AS
    SELECT
        DATE_TRUNC('DAY', s.EVENT_TIMESTAMP) AS COST_DATE,
        s.WAREHOUSE_NAME,
        s.USER_NAME,
        s.ROLE_NAME,
        COUNT(DISTINCT s.QUERY_ID) AS QUERY_COUNT,
        SUM(s.CREDITS_USED) AS TOTAL_CREDITS,
        AVG(s.EXECUTION_TIME_MS) AS AVG_EXECUTION_MS,
        SUM(s.BYTES_SCANNED) AS TOTAL_BYTES_SCANNED,
        SUM(s.ROWS_PRODUCED) AS TOTAL_ROWS_PRODUCED,
        SUM(CASE WHEN s.ERROR_CODE IS NOT NULL THEN 1 ELSE 0 END) AS FAILED_QUERIES,
        SUM(s.CREDITS_USED) / NULLIF(COUNT(DISTINCT s.QUERY_ID), 0) AS CREDITS_PER_QUERY
    FROM OBSERVABILITY_PLATFORM.RAW_TELEMETRY.RAW_SNOWFLAKE_TELEMETRY s
    WHERE s.TELEMETRY_TYPE = 'QUERY_HISTORY'
        AND s.EVENT_TIMESTAMP >= DATEADD('DAY', -90, CURRENT_TIMESTAMP())
    GROUP BY ALL;

-- ============================================================================
-- SECTION 8: CONTEXT GRAPH - SERVICE DEPENDENCY MAPPING
-- ============================================================================

USE SCHEMA CONTEXT_GRAPH;

CREATE TABLE IF NOT EXISTS SERVICE_REGISTRY (
    SERVICE_ID VARCHAR(64) DEFAULT UUID_STRING(),
    SERVICE_NAME VARCHAR(256) NOT NULL,
    SERVICE_TYPE VARCHAR(64),
    TEAM_OWNER VARCHAR(256),
    TIER VARCHAR(16),
    ENVIRONMENT VARCHAR(64),
    REPOSITORY_URL VARCHAR(512),
    DOCUMENTATION_URL VARCHAR(512),
    ON_CALL_CHANNEL VARCHAR(256),
    SLO_AVAILABILITY DOUBLE DEFAULT 0.999,
    SLO_LATENCY_P99_MS INT DEFAULT 2000,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METADATA VARIANT,
    CONSTRAINT PK_SERVICE_REGISTRY PRIMARY KEY (SERVICE_ID),
    CONSTRAINT UQ_SERVICE_NAME UNIQUE (SERVICE_NAME, ENVIRONMENT)
);

CREATE TABLE IF NOT EXISTS SERVICE_DEPENDENCIES (
    DEPENDENCY_ID VARCHAR(64) DEFAULT UUID_STRING(),
    SOURCE_SERVICE VARCHAR(256) NOT NULL,
    TARGET_SERVICE VARCHAR(256) NOT NULL,
    DEPENDENCY_TYPE VARCHAR(64),
    PROTOCOL VARCHAR(32),
    IS_CRITICAL BOOLEAN DEFAULT FALSE,
    DISCOVERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_SEEN_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    AVG_CALL_RATE_PER_MIN DOUBLE,
    AVG_LATENCY_MS DOUBLE,
    ERROR_RATE DOUBLE,
    METADATA VARIANT
);

CREATE OR REPLACE DYNAMIC TABLE DT_AUTO_DISCOVERED_DEPENDENCIES
    TARGET_LAG = '15 minutes'
    WAREHOUSE = TRANSFORM_WH
AS
    SELECT
        t.SERVICE_NAME AS SOURCE_SERVICE,
        t.SPAN_ATTRIBUTES:"peer.service"::VARCHAR AS TARGET_SERVICE,
        t.SPAN_KIND AS CALL_TYPE,
        COUNT(*) AS CALL_COUNT,
        AVG(t.DURATION_MS) AS AVG_LATENCY_MS,
        SUM(CASE WHEN t.IS_ERROR THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) AS ERROR_RATE,
        MIN(t.START_TIME) AS FIRST_SEEN,
        MAX(t.START_TIME) AS LAST_SEEN
    FROM OBSERVABILITY_PLATFORM.SILVER.DT_ENRICHED_TRACES t
    WHERE t.SPAN_ATTRIBUTES:"peer.service" IS NOT NULL
        AND t.START_TIME >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
    GROUP BY ALL;

-- ============================================================================
-- SECTION 9: AI SRE - ANOMALY DETECTION & INCIDENT ANALYSIS
-- ============================================================================

USE SCHEMA AI_SRE;

CREATE TABLE IF NOT EXISTS INCIDENTS (
    INCIDENT_ID VARCHAR(64) DEFAULT UUID_STRING(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT TIMESTAMP_NTZ,
    SEVERITY VARCHAR(16) NOT NULL,
    STATUS VARCHAR(32) DEFAULT 'OPEN',
    TITLE VARCHAR(1024) NOT NULL,
    DESCRIPTION TEXT,
    SERVICE_NAME VARCHAR(256),
    ENVIRONMENT VARCHAR(64),
    ROOT_CAUSE TEXT,
    REMEDIATION_ACTIONS TEXT,
    AI_SUMMARY TEXT,
    AI_ROOT_CAUSE TEXT,
    AI_RECOMMENDATIONS TEXT,
    TTDA_MINUTES DOUBLE,
    TTTA_MINUTES DOUBLE,
    TTTR_MINUTES DOUBLE,
    ASSIGNED_TEAM VARCHAR(256),
    RELATED_TRACES ARRAY,
    RELATED_LOGS ARRAY,
    METADATA VARIANT
);

CREATE TABLE IF NOT EXISTS ANOMALY_DETECTIONS (
    ANOMALY_ID VARCHAR(64) DEFAULT UUID_STRING(),
    DETECTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METRIC_NAME VARCHAR(512),
    SERVICE_NAME VARCHAR(256),
    ENVIRONMENT VARCHAR(64),
    EXPECTED_VALUE DOUBLE,
    ACTUAL_VALUE DOUBLE,
    DEVIATION_SCORE DOUBLE,
    ANOMALY_TYPE VARCHAR(64),
    IS_ACKNOWLEDGED BOOLEAN DEFAULT FALSE,
    RELATED_INCIDENT_ID VARCHAR(64),
    CONTEXT VARIANT
);

CREATE TABLE IF NOT EXISTS AI_SRE_ACTIONS (
    ACTION_ID VARCHAR(64) DEFAULT UUID_STRING(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INCIDENT_ID VARCHAR(64),
    ACTION_TYPE VARCHAR(64),
    ACTION_DESCRIPTION TEXT,
    AI_MODEL_USED VARCHAR(128),
    INPUT_CONTEXT TEXT,
    AI_OUTPUT TEXT,
    CONFIDENCE_SCORE DOUBLE,
    WAS_APPROVED BOOLEAN,
    EXECUTED_AT TIMESTAMP_NTZ,
    EXECUTION_RESULT TEXT
);

CREATE TABLE IF NOT EXISTS RUNBOOKS (
    RUNBOOK_ID VARCHAR(64) DEFAULT UUID_STRING(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TITLE VARCHAR(512) NOT NULL,
    SERVICE_NAME VARCHAR(256),
    TRIGGER_CONDITION TEXT,
    STEPS TEXT NOT NULL,
    AUTOMATION_LEVEL VARCHAR(32) DEFAULT 'MANUAL',
    LAST_EXECUTED_AT TIMESTAMP_NTZ,
    EXECUTION_COUNT INT DEFAULT 0,
    AVG_RESOLUTION_MINUTES DOUBLE,
    EMBEDDING VECTOR(FLOAT, 768)
);

-- Cortex Search Service for Runbook RAG
-- NOTE: Requires non-trial account for embedding model access.
-- Uncomment below when upgraded to a paid account.
/*
CREATE OR REPLACE CORTEX SEARCH SERVICE AI_SRE_RUNBOOK_SEARCH
    ON STEPS
    ATTRIBUTES SERVICE_NAME
    WAREHOUSE = AI_SRE_WH
    TARGET_LAG = '1 day'
    EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
AS (
    SELECT
        RUNBOOK_ID,
        TITLE,
        SERVICE_NAME,
        TRIGGER_CONDITION,
        STEPS,
        AUTOMATION_LEVEL
    FROM OBSERVABILITY_PLATFORM.AI_SRE.RUNBOOKS
);
*/

-- ============================================================================
-- SECTION 10: ALERTING FRAMEWORK
-- ============================================================================

USE SCHEMA ALERTING;

CREATE TABLE IF NOT EXISTS ALERT_RULES (
    RULE_ID VARCHAR(64) DEFAULT UUID_STRING(),
    RULE_NAME VARCHAR(512) NOT NULL,
    DESCRIPTION TEXT,
    SERVICE_NAME VARCHAR(256),
    METRIC_NAME VARCHAR(512),
    CONDITION_SQL TEXT NOT NULL,
    THRESHOLD_VALUE DOUBLE,
    COMPARISON_OPERATOR VARCHAR(8),
    EVALUATION_WINDOW_MINUTES INT DEFAULT 5,
    SEVERITY VARCHAR(16) DEFAULT 'WARNING',
    NOTIFICATION_CHANNELS ARRAY,
    IS_ENABLED BOOLEAN DEFAULT TRUE,
    COOLDOWN_MINUTES INT DEFAULT 15,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_TRIGGERED_AT TIMESTAMP_NTZ,
    TRIGGER_COUNT INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ALERT_HISTORY (
    ALERT_ID VARCHAR(64) DEFAULT UUID_STRING(),
    TRIGGERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RULE_ID VARCHAR(64) NOT NULL,
    RULE_NAME VARCHAR(512),
    SEVERITY VARCHAR(16),
    SERVICE_NAME VARCHAR(256),
    METRIC_VALUE DOUBLE,
    THRESHOLD_VALUE DOUBLE,
    ALERT_MESSAGE TEXT,
    ACKNOWLEDGED_AT TIMESTAMP_NTZ,
    ACKNOWLEDGED_BY VARCHAR(256),
    RESOLVED_AT TIMESTAMP_NTZ,
    NOTIFICATION_SENT BOOLEAN DEFAULT FALSE,
    RELATED_INCIDENT_ID VARCHAR(64)
);

-- Alert evaluation task
CREATE OR REPLACE TASK EVALUATE_ALERTS
    WAREHOUSE = AI_SRE_WH
    SCHEDULE = '1 MINUTE'
AS
    INSERT INTO OBSERVABILITY_PLATFORM.ALERTING.ALERT_HISTORY (
        RULE_ID, RULE_NAME, SEVERITY, SERVICE_NAME,
        METRIC_VALUE, THRESHOLD_VALUE, ALERT_MESSAGE
    )
    SELECT
        ar.RULE_ID,
        ar.RULE_NAME,
        ar.SEVERITY,
        ar.SERVICE_NAME,
        sh.HEALTH_SCORE AS METRIC_VALUE,
        ar.THRESHOLD_VALUE,
        'Service ' || ar.SERVICE_NAME || ' health score dropped to ' || sh.HEALTH_SCORE::VARCHAR
    FROM OBSERVABILITY_PLATFORM.ALERTING.ALERT_RULES ar
    JOIN OBSERVABILITY_PLATFORM.GOLD.DT_SERVICE_HEALTH_SCORE sh
        ON ar.SERVICE_NAME = sh.SERVICE_NAME
    WHERE ar.IS_ENABLED = TRUE
        AND ar.METRIC_NAME = 'health_score'
        AND sh.HEALTH_SCORE < ar.THRESHOLD_VALUE
        AND sh.HOUR_BUCKET = DATE_TRUNC('HOUR', CURRENT_TIMESTAMP())
        AND (ar.LAST_TRIGGERED_AT IS NULL OR
             DATEDIFF('MINUTE', ar.LAST_TRIGGERED_AT, CURRENT_TIMESTAMP()) > ar.COOLDOWN_MINUTES);

ALTER TASK EVALUATE_ALERTS RESUME;

-- ============================================================================
-- SECTION 11: GOVERNANCE & SECURITY POLICIES
-- ============================================================================

USE SCHEMA GOVERNANCE;

CREATE MASKING POLICY IF NOT EXISTS MASK_LOG_PII AS (VAL TEXT) RETURNS TEXT ->
    CASE
        WHEN CURRENT_ROLE() IN ('OBSERVABILITY_ADMIN', 'GOVERNANCE_OFFICER') THEN VAL
        WHEN CURRENT_ROLE() = 'OBSERVABILITY_ENGINEER' THEN REGEXP_REPLACE(VAL, '[0-9]{3}-[0-9]{2}-[0-9]{4}', '***-**-****')
        ELSE '*** MASKED ***'
    END;

CREATE MASKING POLICY IF NOT EXISTS MASK_QUERY_TEXT AS (VAL TEXT) RETURNS TEXT ->
    CASE
        WHEN CURRENT_ROLE() IN ('OBSERVABILITY_ADMIN', 'OBSERVABILITY_ENGINEER') THEN VAL
        ELSE LEFT(VAL, 50) || '... [REDACTED]'
    END;

CREATE ROW ACCESS POLICY IF NOT EXISTS ENVIRONMENT_ACCESS AS (ENV VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('OBSERVABILITY_ADMIN', 'OBSERVABILITY_ENGINEER') THEN TRUE
        WHEN CURRENT_ROLE() = 'OBSERVABILITY_ANALYST' AND ENV IN ('production', 'staging') THEN TRUE
        WHEN CURRENT_ROLE() = 'OBSERVABILITY_VIEWER' AND ENV = 'production' THEN TRUE
        ELSE FALSE
    END;

ALTER TABLE OBSERVABILITY_PLATFORM.RAW_TELEMETRY.RAW_LOGS
    ADD ROW ACCESS POLICY OBSERVABILITY_PLATFORM.GOVERNANCE.ENVIRONMENT_ACCESS ON (ENVIRONMENT);

ALTER TABLE OBSERVABILITY_PLATFORM.RAW_TELEMETRY.RAW_SNOWFLAKE_TELEMETRY
    MODIFY COLUMN QUERY_TEXT SET MASKING POLICY OBSERVABILITY_PLATFORM.GOVERNANCE.MASK_QUERY_TEXT;

CREATE TABLE IF NOT EXISTS DATA_RETENTION_POLICIES (
    POLICY_ID VARCHAR(64) DEFAULT UUID_STRING(),
    TABLE_NAME VARCHAR(512) NOT NULL,
    RETENTION_DAYS INT NOT NULL,
    ARCHIVE_STRATEGY VARCHAR(32) DEFAULT 'DELETE',
    LAST_CLEANUP_AT TIMESTAMP_NTZ,
    NEXT_CLEANUP_AT TIMESTAMP_NTZ,
    IS_ENABLED BOOLEAN DEFAULT TRUE
);

INSERT INTO DATA_RETENTION_POLICIES (TABLE_NAME, RETENTION_DAYS, ARCHIVE_STRATEGY)
VALUES
    ('RAW_TELEMETRY.RAW_LOGS', 90, 'DELETE'),
    ('RAW_TELEMETRY.RAW_METRICS', 365, 'ARCHIVE_TO_ICEBERG'),
    ('RAW_TELEMETRY.RAW_TRACES', 30, 'DELETE'),
    ('RAW_TELEMETRY.RAW_K8S_EVENTS', 90, 'DELETE'),
    ('AI_SRE.INCIDENTS', 730, 'ARCHIVE_TO_ICEBERG'),
    ('ALERTING.ALERT_HISTORY', 365, 'DELETE');

-- Retention enforcement task
CREATE OR REPLACE TASK ENFORCE_RETENTION
    WAREHOUSE = TRANSFORM_WH
    SCHEDULE = 'USING CRON 0 2 * * * America/Los_Angeles'
AS
    DELETE FROM OBSERVABILITY_PLATFORM.RAW_TELEMETRY.RAW_LOGS
    WHERE LOG_TIMESTAMP < DATEADD('DAY', -90, CURRENT_TIMESTAMP());

ALTER TASK ENFORCE_RETENTION RESUME;

-- ============================================================================
-- SECTION 12: COST MONITORING & OPTIMIZATION
-- ============================================================================

USE SCHEMA COST_OPS;

CREATE OR REPLACE VIEW V_DAILY_CREDIT_CONSUMPTION AS
    SELECT
        DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
        WAREHOUSE_NAME,
        SUM(CREDITS_USED) AS CREDITS_USED,
        SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
        SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE START_TIME >= DATEADD('DAY', -90, CURRENT_TIMESTAMP())
    GROUP BY ALL
    ORDER BY USAGE_DATE DESC, CREDITS_USED DESC;

CREATE OR REPLACE VIEW V_AI_SERVICES_COST AS
    SELECT
        USAGE_DATE,
        SERVICE_TYPE,
        SUM(CREDITS_USED) AS CREDITS_USED
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
    WHERE SERVICE_TYPE = 'AI_SERVICES'
        AND USAGE_DATE >= DATEADD('DAY', -90, CURRENT_DATE())
    GROUP BY ALL
    ORDER BY USAGE_DATE DESC;

CREATE OR REPLACE VIEW V_STORAGE_COST_ANALYSIS AS
    SELECT
        TABLE_CATALOG AS DATABASE_NAME,
        TABLE_SCHEMA AS SCHEMA_NAME,
        TABLE_NAME,
        ACTIVE_BYTES / POWER(1024, 3) AS ACTIVE_SIZE_GB,
        TIME_TRAVEL_BYTES / POWER(1024, 3) AS TIME_TRAVEL_GB,
        FAILSAFE_BYTES / POWER(1024, 3) AS FAILSAFE_GB,
        (ACTIVE_BYTES + TIME_TRAVEL_BYTES + FAILSAFE_BYTES) / POWER(1024, 3) AS TOTAL_SIZE_GB,
        TABLE_CREATED
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
    WHERE TABLE_CATALOG = 'OBSERVABILITY_PLATFORM'
        AND DELETED IS NULL
    ORDER BY ACTIVE_BYTES DESC;
